# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-23 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetrainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='doj',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
