# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-23 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managetrainer', '0002_auto_20190623_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='id',
        ),
        migrations.AddField(
            model_name='trainer',
            name='emp_id',
            field=models.CharField(default=datetime.datetime(2019, 6, 23, 17, 0, 48, 836220, tzinfo=utc), max_length=45, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
