# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-24 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetrainer', '0003_auto_20190623_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='designation',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='doj',
            field=models.DateField(),
        ),
    ]
