# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-17 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managetrainer', '0006_trainer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='profile_pic',
        ),
    ]
